### ISSUE TITLE
[ENHANCEMENT]-> Create a new screen

### ISSUE THREAD

**Issue by mrudulmohan007** [mrudulmohan007/Rent-ok-property-app#1]
Create a screen based on the design provided below

https://github.com/mrudulmohan007/Rent-ok-property-app/assets/80639314/a52f2f69-9637-4fb6-a5e5-fd725fd2783a

**Comment by Mrudul111** [comment]
could you assign me this issue?

**Comment by mrudulmohan007** [comment]
Yes brother sure

**Comment by Mrudul111** [comment]
Do you have figma for the screen?

**Comment by mrudulmohan007** [comment]
No bro  , this app is available there in play store you can refer it, name is : RentOk(EazyPG)

**Comment by Mrudul111** [comment]
issued a PR pls check it once and merge it if its okay and let me know any changes that I should make

**Comment by mrudulmohan007** [comment]
ok bro its fine done

**Comment by mrudulmohan007** [comment]
issue closed
