### ISSUE TITLE
[ENHANCEMENT]- create a homepage

### ISSUE THREAD

**Issue by mrudulmohan007** [mrudulmohan007/Rent-ok-property-app#3]
Create the contents of the  home page as i show below in the video(finish the part till i scrolled in the video)

for your reference : app shown below is RentOk(EasyPG) app which is available only on playstore

https://github.com/mrudulmohan007/Rent-ok-property-app/assets/80639314/42a17207-5776-449e-9bec-67456f193cd0

**Comment by original-subbaman** [comment]
I could help you with this if you assign it to me.

**Comment by mrudulmohan007** [comment]
yeah bro done

**Comment by original-subbaman** [comment]
Have you looked at the code? Did it help?

**Comment by mrudulmohan007** [comment]
yes broo its fine
