### ISSUE TITLE
Request To Add Splash screen and login Screens

### ISSUE THREAD

**Issue by SaadTanveer14** [mrudulmohan007/Rent-ok-property-app#6]
hello guys, 
I want to add splash screen and login and signup screens for this projects. 
![s2](https://github.com/mrudulmohan007/Rent-ok-property-app/assets/99664282/b3ca7caa-7f10-425a-8bdc-809d7a555cdb)
![s1](https://github.com/mrudulmohan007/Rent-ok-property-app/assets/99664282/b945be1f-3e56-4523-8512-29d837377457)

**Comment by Aryashakya** [comment]
Hi, I would like to work on this.
